name: Upload Release Info

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: npm i -g ircbloq-resource-cli@latest

      # Fetch the release info and upload to digitalocean
      - name: Release resources to digital ocean spaces
        run: |
          export DO_KEY_ID=${{ secrets.DO_KEY_ID }}
          export DO_SECRET_KEY=${{ secrets.DO_SECRET_KEY }}
          upload-releaseInfo